// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package unity.proxies;

public class UnityContext
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject unityContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Unity.UnityContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SelectedPipeName("SelectedPipeName");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public UnityContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Unity.UnityContext"));
	}

	protected UnityContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject unityContextMendixObject)
	{
		if (unityContextMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Unity.UnityContext", unityContextMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Unity.UnityContext");

		this.unityContextMendixObject = unityContextMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'UnityContext.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static unity.proxies.UnityContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return unity.proxies.UnityContext.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static unity.proxies.UnityContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new unity.proxies.UnityContext(context, mendixObject);
	}

	public static unity.proxies.UnityContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return unity.proxies.UnityContext.initialize(context, mendixObject);
	}

	public static java.util.List<unity.proxies.UnityContext> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<unity.proxies.UnityContext> result = new java.util.ArrayList<unity.proxies.UnityContext>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Unity.UnityContext" + xpathConstraint))
			result.add(unity.proxies.UnityContext.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SelectedPipeName
	 */
	public final java.lang.String getSelectedPipeName()
	{
		return getSelectedPipeName(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectedPipeName
	 */
	public final java.lang.String getSelectedPipeName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SelectedPipeName.toString());
	}

	/**
	 * Set value of SelectedPipeName
	 * @param selectedpipename
	 */
	public final void setSelectedPipeName(java.lang.String selectedpipename)
	{
		setSelectedPipeName(getContext(), selectedpipename);
	}

	/**
	 * Set value of SelectedPipeName
	 * @param context
	 * @param selectedpipename
	 */
	public final void setSelectedPipeName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String selectedpipename)
	{
		getMendixObject().setValue(context, MemberNames.SelectedPipeName.toString(), selectedpipename);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return unityContextMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final unity.proxies.UnityContext that = (unity.proxies.UnityContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Unity.UnityContext";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
