// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amap.proxies;

public class AMapContext2
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aMapContext2MendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AMap.AMapContext2";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Lat("Lat"),
		Lng("Lng"),
		Lng_2("Lng_2"),
		Lat_2("Lat_2");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AMapContext2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AMap.AMapContext2"));
	}

	protected AMapContext2(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aMapContext2MendixObject)
	{
		if (aMapContext2MendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AMap.AMapContext2", aMapContext2MendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AMap.AMapContext2");

		this.aMapContext2MendixObject = aMapContext2MendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AMapContext2.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static amap.proxies.AMapContext2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return amap.proxies.AMapContext2.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static amap.proxies.AMapContext2 initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amap.proxies.AMapContext2(context, mendixObject);
	}

	public static amap.proxies.AMapContext2 load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amap.proxies.AMapContext2.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Lat
	 */
	public final java.math.BigDecimal getLat()
	{
		return getLat(getContext());
	}

	/**
	 * @param context
	 * @return value of Lat
	 */
	public final java.math.BigDecimal getLat(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lat.toString());
	}

	/**
	 * Set value of Lat
	 * @param lat
	 */
	public final void setLat(java.math.BigDecimal lat)
	{
		setLat(getContext(), lat);
	}

	/**
	 * Set value of Lat
	 * @param context
	 * @param lat
	 */
	public final void setLat(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lat)
	{
		getMendixObject().setValue(context, MemberNames.Lat.toString(), lat);
	}

	/**
	 * @return value of Lng
	 */
	public final java.math.BigDecimal getLng()
	{
		return getLng(getContext());
	}

	/**
	 * @param context
	 * @return value of Lng
	 */
	public final java.math.BigDecimal getLng(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lng.toString());
	}

	/**
	 * Set value of Lng
	 * @param lng
	 */
	public final void setLng(java.math.BigDecimal lng)
	{
		setLng(getContext(), lng);
	}

	/**
	 * Set value of Lng
	 * @param context
	 * @param lng
	 */
	public final void setLng(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lng)
	{
		getMendixObject().setValue(context, MemberNames.Lng.toString(), lng);
	}

	/**
	 * @return value of Lng_2
	 */
	public final java.math.BigDecimal getLng_2()
	{
		return getLng_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Lng_2
	 */
	public final java.math.BigDecimal getLng_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lng_2.toString());
	}

	/**
	 * Set value of Lng_2
	 * @param lng_2
	 */
	public final void setLng_2(java.math.BigDecimal lng_2)
	{
		setLng_2(getContext(), lng_2);
	}

	/**
	 * Set value of Lng_2
	 * @param context
	 * @param lng_2
	 */
	public final void setLng_2(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lng_2)
	{
		getMendixObject().setValue(context, MemberNames.Lng_2.toString(), lng_2);
	}

	/**
	 * @return value of Lat_2
	 */
	public final java.math.BigDecimal getLat_2()
	{
		return getLat_2(getContext());
	}

	/**
	 * @param context
	 * @return value of Lat_2
	 */
	public final java.math.BigDecimal getLat_2(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Lat_2.toString());
	}

	/**
	 * Set value of Lat_2
	 * @param lat_2
	 */
	public final void setLat_2(java.math.BigDecimal lat_2)
	{
		setLat_2(getContext(), lat_2);
	}

	/**
	 * Set value of Lat_2
	 * @param context
	 * @param lat_2
	 */
	public final void setLat_2(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lat_2)
	{
		getMendixObject().setValue(context, MemberNames.Lat_2.toString(), lat_2);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aMapContext2MendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amap.proxies.AMapContext2 that = (amap.proxies.AMapContext2) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AMap.AMapContext2";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
