// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amap.proxies;

public class DriveStep
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject driveStepMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AMap.DriveStep";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		instruction("instruction"),
		action("action"),
		DriveStep_DriveRoute_steps("AMap.DriveStep_DriveRoute_steps"),
		DriveRoute_DriveStep_focus("AMap.DriveRoute_DriveStep_focus");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DriveStep(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AMap.DriveStep"));
	}

	protected DriveStep(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject driveStepMendixObject)
	{
		if (driveStepMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AMap.DriveStep", driveStepMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AMap.DriveStep");

		this.driveStepMendixObject = driveStepMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DriveStep.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static amap.proxies.DriveStep initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return amap.proxies.DriveStep.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static amap.proxies.DriveStep initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amap.proxies.DriveStep(context, mendixObject);
	}

	public static amap.proxies.DriveStep load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amap.proxies.DriveStep.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of instruction
	 */
	public final java.lang.String getinstruction()
	{
		return getinstruction(getContext());
	}

	/**
	 * @param context
	 * @return value of instruction
	 */
	public final java.lang.String getinstruction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.instruction.toString());
	}

	/**
	 * Set value of instruction
	 * @param instruction
	 */
	public final void setinstruction(java.lang.String instruction)
	{
		setinstruction(getContext(), instruction);
	}

	/**
	 * Set value of instruction
	 * @param context
	 * @param instruction
	 */
	public final void setinstruction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String instruction)
	{
		getMendixObject().setValue(context, MemberNames.instruction.toString(), instruction);
	}

	/**
	 * @return value of action
	 */
	public final java.lang.String getaction()
	{
		return getaction(getContext());
	}

	/**
	 * @param context
	 * @return value of action
	 */
	public final java.lang.String getaction(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.action.toString());
	}

	/**
	 * Set value of action
	 * @param action
	 */
	public final void setaction(java.lang.String action)
	{
		setaction(getContext(), action);
	}

	/**
	 * Set value of action
	 * @param context
	 * @param action
	 */
	public final void setaction(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String action)
	{
		getMendixObject().setValue(context, MemberNames.action.toString(), action);
	}

	/**
	 * @return value of DriveStep_DriveRoute_steps
	 */
	public final amap.proxies.DriveRoute getDriveStep_DriveRoute_steps() throws com.mendix.core.CoreException
	{
		return getDriveStep_DriveRoute_steps(getContext());
	}

	/**
	 * @param context
	 * @return value of DriveStep_DriveRoute_steps
	 */
	public final amap.proxies.DriveRoute getDriveStep_DriveRoute_steps(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amap.proxies.DriveRoute result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DriveStep_DriveRoute_steps.toString());
		if (identifier != null)
			result = amap.proxies.DriveRoute.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DriveStep_DriveRoute_steps
	 * @param drivestep_driveroute_steps
	 */
	public final void setDriveStep_DriveRoute_steps(amap.proxies.DriveRoute drivestep_driveroute_steps)
	{
		setDriveStep_DriveRoute_steps(getContext(), drivestep_driveroute_steps);
	}

	/**
	 * Set value of DriveStep_DriveRoute_steps
	 * @param context
	 * @param drivestep_driveroute_steps
	 */
	public final void setDriveStep_DriveRoute_steps(com.mendix.systemwideinterfaces.core.IContext context, amap.proxies.DriveRoute drivestep_driveroute_steps)
	{
		if (drivestep_driveroute_steps == null)
			getMendixObject().setValue(context, MemberNames.DriveStep_DriveRoute_steps.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DriveStep_DriveRoute_steps.toString(), drivestep_driveroute_steps.getMendixObject().getId());
	}

	/**
	 * @return value of DriveRoute_DriveStep_focus
	 */
	public final amap.proxies.DriveRoute getDriveRoute_DriveStep_focus() throws com.mendix.core.CoreException
	{
		return getDriveRoute_DriveStep_focus(getContext());
	}

	/**
	 * @param context
	 * @return value of DriveRoute_DriveStep_focus
	 */
	public final amap.proxies.DriveRoute getDriveRoute_DriveStep_focus(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amap.proxies.DriveRoute result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DriveRoute_DriveStep_focus.toString());
		if (identifier != null)
			result = amap.proxies.DriveRoute.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DriveRoute_DriveStep_focus
	 * @param driveroute_drivestep_focus
	 */
	public final void setDriveRoute_DriveStep_focus(amap.proxies.DriveRoute driveroute_drivestep_focus)
	{
		setDriveRoute_DriveStep_focus(getContext(), driveroute_drivestep_focus);
	}

	/**
	 * Set value of DriveRoute_DriveStep_focus
	 * @param context
	 * @param driveroute_drivestep_focus
	 */
	public final void setDriveRoute_DriveStep_focus(com.mendix.systemwideinterfaces.core.IContext context, amap.proxies.DriveRoute driveroute_drivestep_focus)
	{
		if (driveroute_drivestep_focus == null)
			getMendixObject().setValue(context, MemberNames.DriveRoute_DriveStep_focus.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DriveRoute_DriveStep_focus.toString(), driveroute_drivestep_focus.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return driveStepMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amap.proxies.DriveStep that = (amap.proxies.DriveStep) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AMap.DriveStep";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
