// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amap.proxies;

public class DrivingResult
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject drivingResultMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AMap.DrivingResult";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		info("info"),
		origin("origin"),
		destination("destination"),
		start("start"),
		end("end"),
		taxi_cost("taxi_cost"),
		DrivingResult_AMapContext("AMap.DrivingResult_AMapContext");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public DrivingResult(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AMap.DrivingResult"));
	}

	protected DrivingResult(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject drivingResultMendixObject)
	{
		if (drivingResultMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AMap.DrivingResult", drivingResultMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AMap.DrivingResult");

		this.drivingResultMendixObject = drivingResultMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'DrivingResult.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static amap.proxies.DrivingResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return amap.proxies.DrivingResult.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static amap.proxies.DrivingResult initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amap.proxies.DrivingResult(context, mendixObject);
	}

	public static amap.proxies.DrivingResult load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amap.proxies.DrivingResult.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of info
	 */
	public final java.lang.String getinfo()
	{
		return getinfo(getContext());
	}

	/**
	 * @param context
	 * @return value of info
	 */
	public final java.lang.String getinfo(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.info.toString());
	}

	/**
	 * Set value of info
	 * @param info
	 */
	public final void setinfo(java.lang.String info)
	{
		setinfo(getContext(), info);
	}

	/**
	 * Set value of info
	 * @param context
	 * @param info
	 */
	public final void setinfo(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String info)
	{
		getMendixObject().setValue(context, MemberNames.info.toString(), info);
	}

	/**
	 * @return value of origin
	 */
	public final java.lang.String getorigin()
	{
		return getorigin(getContext());
	}

	/**
	 * @param context
	 * @return value of origin
	 */
	public final java.lang.String getorigin(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.origin.toString());
	}

	/**
	 * Set value of origin
	 * @param origin
	 */
	public final void setorigin(java.lang.String origin)
	{
		setorigin(getContext(), origin);
	}

	/**
	 * Set value of origin
	 * @param context
	 * @param origin
	 */
	public final void setorigin(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String origin)
	{
		getMendixObject().setValue(context, MemberNames.origin.toString(), origin);
	}

	/**
	 * @return value of destination
	 */
	public final java.lang.String getdestination()
	{
		return getdestination(getContext());
	}

	/**
	 * @param context
	 * @return value of destination
	 */
	public final java.lang.String getdestination(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.destination.toString());
	}

	/**
	 * Set value of destination
	 * @param destination
	 */
	public final void setdestination(java.lang.String destination)
	{
		setdestination(getContext(), destination);
	}

	/**
	 * Set value of destination
	 * @param context
	 * @param destination
	 */
	public final void setdestination(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String destination)
	{
		getMendixObject().setValue(context, MemberNames.destination.toString(), destination);
	}

	/**
	 * @return value of start
	 */
	public final java.lang.String getstart()
	{
		return getstart(getContext());
	}

	/**
	 * @param context
	 * @return value of start
	 */
	public final java.lang.String getstart(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.start.toString());
	}

	/**
	 * Set value of start
	 * @param start
	 */
	public final void setstart(java.lang.String start)
	{
		setstart(getContext(), start);
	}

	/**
	 * Set value of start
	 * @param context
	 * @param start
	 */
	public final void setstart(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String start)
	{
		getMendixObject().setValue(context, MemberNames.start.toString(), start);
	}

	/**
	 * @return value of end
	 */
	public final java.lang.String getend()
	{
		return getend(getContext());
	}

	/**
	 * @param context
	 * @return value of end
	 */
	public final java.lang.String getend(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.end.toString());
	}

	/**
	 * Set value of end
	 * @param end
	 */
	public final void setend(java.lang.String end)
	{
		setend(getContext(), end);
	}

	/**
	 * Set value of end
	 * @param context
	 * @param end
	 */
	public final void setend(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String end)
	{
		getMendixObject().setValue(context, MemberNames.end.toString(), end);
	}

	/**
	 * @return value of taxi_cost
	 */
	public final java.math.BigDecimal gettaxi_cost()
	{
		return gettaxi_cost(getContext());
	}

	/**
	 * @param context
	 * @return value of taxi_cost
	 */
	public final java.math.BigDecimal gettaxi_cost(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.taxi_cost.toString());
	}

	/**
	 * Set value of taxi_cost
	 * @param taxi_cost
	 */
	public final void settaxi_cost(java.math.BigDecimal taxi_cost)
	{
		settaxi_cost(getContext(), taxi_cost);
	}

	/**
	 * Set value of taxi_cost
	 * @param context
	 * @param taxi_cost
	 */
	public final void settaxi_cost(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal taxi_cost)
	{
		getMendixObject().setValue(context, MemberNames.taxi_cost.toString(), taxi_cost);
	}

	/**
	 * @return value of DrivingResult_AMapContext
	 */
	public final amap.proxies.AMapContext getDrivingResult_AMapContext() throws com.mendix.core.CoreException
	{
		return getDrivingResult_AMapContext(getContext());
	}

	/**
	 * @param context
	 * @return value of DrivingResult_AMapContext
	 */
	public final amap.proxies.AMapContext getDrivingResult_AMapContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amap.proxies.AMapContext result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.DrivingResult_AMapContext.toString());
		if (identifier != null)
			result = amap.proxies.AMapContext.load(context, identifier);
		return result;
	}

	/**
	 * Set value of DrivingResult_AMapContext
	 * @param drivingresult_amapcontext
	 */
	public final void setDrivingResult_AMapContext(amap.proxies.AMapContext drivingresult_amapcontext)
	{
		setDrivingResult_AMapContext(getContext(), drivingresult_amapcontext);
	}

	/**
	 * Set value of DrivingResult_AMapContext
	 * @param context
	 * @param drivingresult_amapcontext
	 */
	public final void setDrivingResult_AMapContext(com.mendix.systemwideinterfaces.core.IContext context, amap.proxies.AMapContext drivingresult_amapcontext)
	{
		if (drivingresult_amapcontext == null)
			getMendixObject().setValue(context, MemberNames.DrivingResult_AMapContext.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.DrivingResult_AMapContext.toString(), drivingresult_amapcontext.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return drivingResultMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amap.proxies.DrivingResult that = (amap.proxies.DrivingResult) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AMap.DrivingResult";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
