// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package amap.proxies;

public class Poi
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject poiMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AMap.Poi";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Poi_DrivingResult_waypoints("AMap.Poi_DrivingResult_waypoints");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Poi(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AMap.Poi"));
	}

	protected Poi(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject poiMendixObject)
	{
		if (poiMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AMap.Poi", poiMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AMap.Poi");

		this.poiMendixObject = poiMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Poi.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static amap.proxies.Poi initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return amap.proxies.Poi.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static amap.proxies.Poi initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new amap.proxies.Poi(context, mendixObject);
	}

	public static amap.proxies.Poi load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return amap.proxies.Poi.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Poi_DrivingResult_waypoints
	 */
	public final amap.proxies.DrivingResult getPoi_DrivingResult_waypoints() throws com.mendix.core.CoreException
	{
		return getPoi_DrivingResult_waypoints(getContext());
	}

	/**
	 * @param context
	 * @return value of Poi_DrivingResult_waypoints
	 */
	public final amap.proxies.DrivingResult getPoi_DrivingResult_waypoints(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		amap.proxies.DrivingResult result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.Poi_DrivingResult_waypoints.toString());
		if (identifier != null)
			result = amap.proxies.DrivingResult.load(context, identifier);
		return result;
	}

	/**
	 * Set value of Poi_DrivingResult_waypoints
	 * @param poi_drivingresult_waypoints
	 */
	public final void setPoi_DrivingResult_waypoints(amap.proxies.DrivingResult poi_drivingresult_waypoints)
	{
		setPoi_DrivingResult_waypoints(getContext(), poi_drivingresult_waypoints);
	}

	/**
	 * Set value of Poi_DrivingResult_waypoints
	 * @param context
	 * @param poi_drivingresult_waypoints
	 */
	public final void setPoi_DrivingResult_waypoints(com.mendix.systemwideinterfaces.core.IContext context, amap.proxies.DrivingResult poi_drivingresult_waypoints)
	{
		if (poi_drivingresult_waypoints == null)
			getMendixObject().setValue(context, MemberNames.Poi_DrivingResult_waypoints.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.Poi_DrivingResult_waypoints.toString(), poi_drivingresult_waypoints.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return poiMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final amap.proxies.Poi that = (amap.proxies.Poi) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AMap.Poi";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
