// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class AMapPageContext
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject aMapPageContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.AMapPageContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Zoom("Zoom"),
		LatCenter("LatCenter"),
		LngCenter("LngCenter");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public AMapPageContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.AMapPageContext"));
	}

	protected AMapPageContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject aMapPageContextMendixObject)
	{
		if (aMapPageContextMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.AMapPageContext", aMapPageContextMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.AMapPageContext");

		this.aMapPageContextMendixObject = aMapPageContextMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'AMapPageContext.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.AMapPageContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.AMapPageContext.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.AMapPageContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.AMapPageContext(context, mendixObject);
	}

	public static myfirstmodule.proxies.AMapPageContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.AMapPageContext.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Zoom
	 */
	public final java.math.BigDecimal getZoom()
	{
		return getZoom(getContext());
	}

	/**
	 * @param context
	 * @return value of Zoom
	 */
	public final java.math.BigDecimal getZoom(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.Zoom.toString());
	}

	/**
	 * Set value of Zoom
	 * @param zoom
	 */
	public final void setZoom(java.math.BigDecimal zoom)
	{
		setZoom(getContext(), zoom);
	}

	/**
	 * Set value of Zoom
	 * @param context
	 * @param zoom
	 */
	public final void setZoom(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal zoom)
	{
		getMendixObject().setValue(context, MemberNames.Zoom.toString(), zoom);
	}

	/**
	 * @return value of LatCenter
	 */
	public final java.math.BigDecimal getLatCenter()
	{
		return getLatCenter(getContext());
	}

	/**
	 * @param context
	 * @return value of LatCenter
	 */
	public final java.math.BigDecimal getLatCenter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.LatCenter.toString());
	}

	/**
	 * Set value of LatCenter
	 * @param latcenter
	 */
	public final void setLatCenter(java.math.BigDecimal latcenter)
	{
		setLatCenter(getContext(), latcenter);
	}

	/**
	 * Set value of LatCenter
	 * @param context
	 * @param latcenter
	 */
	public final void setLatCenter(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal latcenter)
	{
		getMendixObject().setValue(context, MemberNames.LatCenter.toString(), latcenter);
	}

	/**
	 * @return value of LngCenter
	 */
	public final java.math.BigDecimal getLngCenter()
	{
		return getLngCenter(getContext());
	}

	/**
	 * @param context
	 * @return value of LngCenter
	 */
	public final java.math.BigDecimal getLngCenter(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.math.BigDecimal) getMendixObject().getValue(context, MemberNames.LngCenter.toString());
	}

	/**
	 * Set value of LngCenter
	 * @param lngcenter
	 */
	public final void setLngCenter(java.math.BigDecimal lngcenter)
	{
		setLngCenter(getContext(), lngcenter);
	}

	/**
	 * Set value of LngCenter
	 * @param context
	 * @param lngcenter
	 */
	public final void setLngCenter(com.mendix.systemwideinterfaces.core.IContext context, java.math.BigDecimal lngcenter)
	{
		getMendixObject().setValue(context, MemberNames.LngCenter.toString(), lngcenter);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return aMapPageContextMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.AMapPageContext that = (myfirstmodule.proxies.AMapPageContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.AMapPageContext";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
