// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package myfirstmodule.proxies;

public class TransferContext
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject transferContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "MyFirstModule.TransferContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		TargetKeys("TargetKeys"),
		TransferOption_TransferContext("MyFirstModule.TransferOption_TransferContext"),
		TransferContext_TransferOption("MyFirstModule.TransferContext_TransferOption");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public TransferContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "MyFirstModule.TransferContext"));
	}

	protected TransferContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject transferContextMendixObject)
	{
		if (transferContextMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("MyFirstModule.TransferContext", transferContextMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a MyFirstModule.TransferContext");

		this.transferContextMendixObject = transferContextMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'TransferContext.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static myfirstmodule.proxies.TransferContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return myfirstmodule.proxies.TransferContext.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static myfirstmodule.proxies.TransferContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new myfirstmodule.proxies.TransferContext(context, mendixObject);
	}

	public static myfirstmodule.proxies.TransferContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return myfirstmodule.proxies.TransferContext.initialize(context, mendixObject);
	}

	public static java.util.List<myfirstmodule.proxies.TransferContext> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.TransferContext> result = new java.util.ArrayList<myfirstmodule.proxies.TransferContext>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//MyFirstModule.TransferContext" + xpathConstraint))
			result.add(myfirstmodule.proxies.TransferContext.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of TargetKeys
	 */
	public final java.lang.String getTargetKeys()
	{
		return getTargetKeys(getContext());
	}

	/**
	 * @param context
	 * @return value of TargetKeys
	 */
	public final java.lang.String getTargetKeys(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.TargetKeys.toString());
	}

	/**
	 * Set value of TargetKeys
	 * @param targetkeys
	 */
	public final void setTargetKeys(java.lang.String targetkeys)
	{
		setTargetKeys(getContext(), targetkeys);
	}

	/**
	 * Set value of TargetKeys
	 * @param context
	 * @param targetkeys
	 */
	public final void setTargetKeys(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String targetkeys)
	{
		getMendixObject().setValue(context, MemberNames.TargetKeys.toString(), targetkeys);
	}

	/**
	 * @return value of TransferOption_TransferContext
	 */
	public final java.util.List<myfirstmodule.proxies.TransferOption> getTransferOption_TransferContext() throws com.mendix.core.CoreException
	{
		return getTransferOption_TransferContext(getContext());
	}

	/**
	 * @param context
	 * @return value of TransferOption_TransferContext
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.TransferOption> getTransferOption_TransferContext(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.TransferOption> result = new java.util.ArrayList<myfirstmodule.proxies.TransferOption>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.TransferOption_TransferContext.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(myfirstmodule.proxies.TransferOption.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of TransferOption_TransferContext
	 * @param transferoption_transfercontext
	 */
	public final void setTransferOption_TransferContext(java.util.List<myfirstmodule.proxies.TransferOption> transferoption_transfercontext)
	{
		setTransferOption_TransferContext(getContext(), transferoption_transfercontext);
	}

	/**
	 * Set value of TransferOption_TransferContext
	 * @param context
	 * @param transferoption_transfercontext
	 */
	public final void setTransferOption_TransferContext(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.TransferOption> transferoption_transfercontext)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (myfirstmodule.proxies.TransferOption proxyObject : transferoption_transfercontext)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.TransferOption_TransferContext.toString(), identifiers);
	}

	/**
	 * @return value of TransferContext_TransferOption
	 */
	public final java.util.List<myfirstmodule.proxies.TransferOption> getTransferContext_TransferOption() throws com.mendix.core.CoreException
	{
		return getTransferContext_TransferOption(getContext());
	}

	/**
	 * @param context
	 * @return value of TransferContext_TransferOption
	 */
	@SuppressWarnings("unchecked")
	public final java.util.List<myfirstmodule.proxies.TransferOption> getTransferContext_TransferOption(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		java.util.List<myfirstmodule.proxies.TransferOption> result = new java.util.ArrayList<myfirstmodule.proxies.TransferOption>();
		Object valueObject = getMendixObject().getValue(context, MemberNames.TransferContext_TransferOption.toString());
		if (valueObject == null)
			return result;
		for (com.mendix.systemwideinterfaces.core.IMendixObject mendixObject : com.mendix.core.Core.retrieveIdList(context, (java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier>) valueObject))
			result.add(myfirstmodule.proxies.TransferOption.initialize(context, mendixObject));
		return result;
	}

	/**
	 * Set value of TransferContext_TransferOption
	 * @param transfercontext_transferoption
	 */
	public final void setTransferContext_TransferOption(java.util.List<myfirstmodule.proxies.TransferOption> transfercontext_transferoption)
	{
		setTransferContext_TransferOption(getContext(), transfercontext_transferoption);
	}

	/**
	 * Set value of TransferContext_TransferOption
	 * @param context
	 * @param transfercontext_transferoption
	 */
	public final void setTransferContext_TransferOption(com.mendix.systemwideinterfaces.core.IContext context, java.util.List<myfirstmodule.proxies.TransferOption> transfercontext_transferoption)
	{
		java.util.List<com.mendix.systemwideinterfaces.core.IMendixIdentifier> identifiers = new java.util.ArrayList<com.mendix.systemwideinterfaces.core.IMendixIdentifier>();
		for (myfirstmodule.proxies.TransferOption proxyObject : transfercontext_transferoption)
			identifiers.add(proxyObject.getMendixObject().getId());
		getMendixObject().setValue(context, MemberNames.TransferContext_TransferOption.toString(), identifiers);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return transferContextMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final myfirstmodule.proxies.TransferContext that = (myfirstmodule.proxies.TransferContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "MyFirstModule.TransferContext";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
