/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[11],{353:function(ha,ca,h){h.r(ca);var ba=h(362),da=h(89),fa=h(32),aa=h(54);ha=function(){function h(){this.mb=this.Wd=this.Cb=this.Qb=null;this.je=!1}h.prototype.clear=function(){Object(fa.b)(this.Qb);this.Cb="";Object(fa.b)(this.Wd);Object(fa.b)(this.mb);this.je=!1};h.prototype.sc=function(){this.Qb=[];this.Wd=[];this.mb=[];this.je=!1};h.prototype.Iu=function(h){for(var w="",f=0,n,x,e;f<h.length;)n=h.charCodeAt(f),9==n?(w+=String.fromCharCode(10),
f++):128>n?(w+=String.fromCharCode(n),f++):191<n&&224>n?(x=h.charCodeAt(f+1),w+=String.fromCharCode((n&31)<<6|x&63),f+=2):(x=h.charCodeAt(f+1),e=h.charCodeAt(f+2),w+=String.fromCharCode((n&15)<<12|(x&63)<<6|e&63),f+=3);return w};h.prototype.initData=function(h){this.Qb=[];this.Wd=[];this.mb=[];this.je=!1;try{var w=new aa.a(h);this.Cb="";w.Ca();if(!w.advance())return;var f=w.current.textContent;this.Cb=f=this.Iu(f);Object(fa.b)(this.Wd);w.advance();f=w.current.textContent;for(var n=f.split(","),x=
Object(da.a)(n);x.Tj();){var e=x.current;try{var r=parseInt(e.trim());this.Wd.push(r)}catch(ua){}}Object(fa.b)(this.Qb);w.advance();f=w.current.textContent;n=f.split(",");for(var y=Object(da.a)(n);y.Tj();){e=y.current;try{r=parseFloat(e.trim()),this.Qb.push(r)}catch(ua){}}Object(fa.b)(this.mb);w.advance();f=w.current.textContent;n=f.split(",");h=[];w=[];f=0;for(var z=Object(da.a)(n);z.Tj();){e=z.current;switch(e){case "Q":f=1;break;case "R":f=2;break;case "S":f=3;break;default:f=0}if(f)h.push(0),
w.push(f);else try{r=parseFloat(e.trim()),h.push(r),w.push(f)}catch(ua){return}}f=0;var ba=h.length;for(z=e=n=0;z<ba;){var ca=w[z];if(0<ca)f=ca,++z,3===f&&(n=h[z],e=h[z+1],z+=2);else if(1===f)for(r=0;8>r;++r)this.mb.push(h[z++]);else if(2===f){var ha=h[z++];var la=h[z++];var na=h[z++];var ta=h[z++];this.mb.push(ha);this.mb.push(la);this.mb.push(na);this.mb.push(la);this.mb.push(na);this.mb.push(ta);this.mb.push(ha);this.mb.push(ta)}else 3===f&&(ha=h[z++],la=n,na=h[z++],ta=e,this.mb.push(ha),this.mb.push(la),
this.mb.push(na),this.mb.push(la),this.mb.push(na),this.mb.push(ta),this.mb.push(ha),this.mb.push(ta))}}catch(ua){return}this.Cb.length&&this.Cb.length===this.Wd.length&&8*this.Cb.length===this.mb.length&&(this.je=!0)};h.prototype.ready=function(){return this.je};h.prototype.Vr=function(){var h=new ba.a;if(!this.Qb.length)return h.Uf(this.Qb,-1,this.Cb,this.mb,0),h;h.Uf(this.Qb,1,this.Cb,this.mb,1);return h};h.prototype.Ce=function(){return this.mb};h.prototype.getData=function(){return{m_Struct:this.Qb,
m_Str:this.Cb,m_Offsets:this.Wd,m_Quads:this.mb,m_Ready:this.je}};return h}();ca["default"]=ha},362:function(ha,ca,h){var ba=h(51),da=h(194),fa=h(375);ha=function(){function h(){this.Bd=0;this.eb=this.wa=this.re=null;this.mc=0;this.Ad=null}h.prototype.sc=function(){this.Bd=-1;this.mc=0;this.Ad=[]};h.prototype.Uf=function(h,y,w,f,n){this.Bd=y;this.mc=n;this.Ad=[];this.re=h;this.wa=w;this.eb=f};h.prototype.Ja=function(h){return this.Bd===h.Bd};h.prototype.ji=function(){return Math.abs(this.re[this.Bd])};
h.prototype.Rj=function(){return 0<this.re[this.Bd]};h.prototype.Ac=function(){var h=this.Rj()?6:10,y=new fa.a;y.Uf(this.re,this.Bd+h,this.Bd,this.wa,this.eb,1);return y};h.prototype.JK=function(h){if(0>h||h>=this.ji()){var y=new fa.a;y.Uf(this.re,-1,-1,this.wa,this.eb,0);return y}var w=this.Rj()?6:10,f=this.Rj()?5:11;y=new fa.a;y.Uf(this.re,this.Bd+w+f*h,this.Bd,this.wa,this.eb,1+h);return y};h.prototype.vf=function(){var z=this.Bd+parseInt(this.re[this.Bd+1]);if(z>=this.re.length){var y=new h;y.Uf(this.re,
-1,this.wa,this.eb,0);return y}y=new h;y.Uf(this.re,z,this.wa,this.eb,this.mc+1);return y};h.prototype.cc=function(h){if(this.Rj())h.fa=this.re[this.Bd+2+0],h.da=this.re[this.Bd+2+1],h.ga=this.re[this.Bd+2+2],h.ea=this.re[this.Bd+2+3];else{for(var y=1.79769E308,w=ba.a.MIN,f=1.79769E308,n=ba.a.MIN,x=0;4>x;++x){var e=this.re[this.Bd+2+2*x],r=this.re[this.Bd+2+2*x+1];y=Math.min(y,e);w=Math.max(w,e);f=Math.min(f,r);n=Math.max(n,r)}h.fa=y;h.da=f;h.ga=w;h.ea=n}};h.prototype.hi=function(){if(this.Ad.length)return this.Ad[0];
var h=new da.a,y=new da.a,w=new fa.a;w.sc();var f=this.Ac(),n=new fa.a;n.sc();for(var x=this.Ac();!x.Ja(w);x=x.We())n=x;w=Array(8);x=Array(8);f.fe(0,w);h.x=(w[0]+w[2]+w[4]+w[6])/4;h.y=(w[1]+w[3]+w[5]+w[7])/4;n.fe(n.Xc()-1,x);y.x=(x[0]+x[2]+x[4]+x[6])/4;y.y=(x[1]+x[3]+x[5]+x[7])/4;.01>Math.abs(h.x-y.x)&&.01>Math.abs(h.y-y.y)&&this.Ad.push(0);h=Math.atan2(y.y-h.y,y.x-h.x);h*=180/3.1415926;0>h&&(h+=360);this.Ad.push(h);return 0};return h}();ca.a=ha},375:function(ha,ca,h){var ba=h(362),da=h(108),fa=h(51);
ha=function(){function h(){this.$i=this.gd=0;this.eb=this.wa=this.Qb=null;this.mc=0}h.prototype.sc=function(){this.$i=this.gd=-1;this.mc=0};h.prototype.Uf=function(h,y,w,f,n,x){this.gd=y;this.$i=w;this.Qb=h;this.wa=f;this.eb=n;this.mc=x};h.prototype.Ja=function(h){return this.gd===h.gd};h.prototype.Xc=function(){return parseInt(this.Qb[this.gd])};h.prototype.fh=function(){return parseInt(this.Qb[this.gd+2])};h.prototype.Hb=function(){return parseInt(this.Qb[this.gd+1])};h.prototype.Rj=function(){return 0<
this.Qb[this.$i]};h.prototype.pX=function(){return Math.abs(this.Qb[this.$i])};h.prototype.We=function(){var z=this.Rj(),y=z?5:11;if(this.gd>=this.$i+(z?6:10)+(this.pX()-1)*y)return z=new h,z.Uf(this.Qb,-1,-1,this.wa,this.eb,0),z;z=new h;z.Uf(this.Qb,this.gd+y,this.$i,this.wa,this.eb,this.mc+1);return z};h.prototype.QW=function(h){var y=this.Xc();return 0>h||h>=y?-1:parseInt(this.Qb[this.gd+1])+h};h.prototype.fe=function(h,y){h=this.QW(h);if(!(0>h)){var w=new ba.a;w.Uf(this.Qb,this.$i,this.wa,this.eb,
0);if(w.Rj()){var f=new da.a;w.cc(f);w=f.da<f.ea?f.da:f.ea;f=f.da>f.ea?f.da:f.ea;h*=8;y[0]=this.eb[h];y[1]=w;y[2]=this.eb[h+2];y[3]=y[1];y[4]=this.eb[h+4];y[5]=f;y[6]=this.eb[h+6];y[7]=y[5]}else for(h*=8,w=0;8>w;++w)y[w]=this.eb[h+w]}};h.prototype.Gd=function(h){var y=new ba.a;y.Uf(this.Qb,this.$i,this.wa,this.eb,0);if(y.Rj()){var w=this.Qb[this.gd+3],f=this.Qb[this.gd+4];if(w>f){var n=w;w=f;f=n}n=new da.a;y.cc(n);y=n.da<n.ea?n.da:n.ea;n=n.da>n.ea?n.da:n.ea;h[0]=w;h[1]=y;h[2]=f;h[3]=y;h[4]=f;h[5]=
n;h[6]=w;h[7]=n}else for(w=this.gd+3,f=0;8>f;++f)h[f]=this.Qb[w+f]};h.prototype.cc=function(h){var y=new ba.a;y.Uf(this.Qb,this.$i,this.wa,this.eb,0);if(y.Rj()){var w=this.Qb[this.gd+3],f=this.Qb[this.gd+4];if(w>f){var n=w;w=f;f=n}n=new da.a;y.cc(n);y=n.da<n.ea?n.da:n.ea;n=n.da>n.ea?n.da:n.ea;h[0]=w;h[1]=y;h[2]=f;h[3]=n}else{w=1.79769E308;f=fa.a.MIN;y=1.79769E308;n=fa.a.MIN;for(var x=this.gd+3,e=0;4>e;++e){var r=this.Qb[x+2*e],z=this.Qb[x+2*e+1];w=Math.min(w,r);f=Math.max(f,r);y=Math.min(y,z);n=Math.max(n,
z)}h[0]=w;h[1]=y;h[2]=f;h[3]=n}};return h}();ca.a=ha}}]);}).call(this || window)
