// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package antselect.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.systemwideinterfaces.core.IMendixObject;

public class Microflows
{
	// These are the microflows for the AntSelect module
	public static void act_Random_20K(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AntSelect.Act_Random_20K").withParams(params).execute(context);
	}
	public static void act_Random_300(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AntSelect.Act_Random_300").withParams(params).execute(context);
	}
	public static void act_Random_5M(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		Core.microflowCall("AntSelect.Act_Random_5M").withParams(params).execute(context);
	}
	public static void act_Random_Data(IContext context, java.lang.Long _radomCount)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("RadomCount", _radomCount);
		Core.microflowCall("AntSelect.Act_Random_Data").withParams(params).execute(context);
	}
	public static antselect.proxies.SelectContext dS_Select(IContext context)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		IMendixObject result = (IMendixObject)Core.microflowCall("AntSelect.DS_Select").withParams(params).execute(context);
		return result == null ? null : antselect.proxies.SelectContext.initialize(context, result);
	}
	public static void onSelect(IContext context, antselect.proxies.SelectContext _selectContext, antselect.proxies.Option _option)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("SelectContext", _selectContext == null ? null : _selectContext.getMendixObject());
		params.put("Option", _option == null ? null : _option.getMendixObject());
		Core.microflowCall("AntSelect.OnSelect").withParams(params).execute(context);
	}
}