// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_web_content.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Atlas_Web_Content module

	public static java.lang.String getAtlas_Web_Content_Version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Atlas_Web_Content.Atlas_Web_Content_Version");
	}
}