// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package antmenu.proxies.microflows;

import java.util.HashMap;
import java.util.Map;
import com.mendix.core.Core;
import com.mendix.core.CoreException;
import com.mendix.systemwideinterfaces.MendixRuntimeException;
import com.mendix.systemwideinterfaces.core.IContext;

public class Microflows
{
	// These are the microflows for the AntMenu module
	public static void act_Open_Menu(IContext context, antmenu.proxies.Menu _menu)
	{
		Map<java.lang.String, Object> params = new HashMap<>();
		params.put("Menu", _menu == null ? null : _menu.getMendixObject());
		Core.microflowCall("AntMenu.Act_Open_Menu").withParams(params).execute(context);
	}
}