// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package antselect.proxies;

public class SelectContext
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject selectContextMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "AntSelect.SelectContext";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		SelectValue("SelectValue"),
		SelectContext_Option("AntSelect.SelectContext_Option");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public SelectContext(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "AntSelect.SelectContext"));
	}

	protected SelectContext(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject selectContextMendixObject)
	{
		if (selectContextMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("AntSelect.SelectContext", selectContextMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a AntSelect.SelectContext");

		this.selectContextMendixObject = selectContextMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'SelectContext.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static antselect.proxies.SelectContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return antselect.proxies.SelectContext.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static antselect.proxies.SelectContext initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new antselect.proxies.SelectContext(context, mendixObject);
	}

	public static antselect.proxies.SelectContext load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return antselect.proxies.SelectContext.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of SelectValue
	 */
	public final java.lang.String getSelectValue()
	{
		return getSelectValue(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectValue
	 */
	public final java.lang.String getSelectValue(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.SelectValue.toString());
	}

	/**
	 * Set value of SelectValue
	 * @param selectvalue
	 */
	public final void setSelectValue(java.lang.String selectvalue)
	{
		setSelectValue(getContext(), selectvalue);
	}

	/**
	 * Set value of SelectValue
	 * @param context
	 * @param selectvalue
	 */
	public final void setSelectValue(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String selectvalue)
	{
		getMendixObject().setValue(context, MemberNames.SelectValue.toString(), selectvalue);
	}

	/**
	 * @return value of SelectContext_Option
	 */
	public final antselect.proxies.Option getSelectContext_Option() throws com.mendix.core.CoreException
	{
		return getSelectContext_Option(getContext());
	}

	/**
	 * @param context
	 * @return value of SelectContext_Option
	 */
	public final antselect.proxies.Option getSelectContext_Option(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		antselect.proxies.Option result = null;
		com.mendix.systemwideinterfaces.core.IMendixIdentifier identifier = getMendixObject().getValue(context, MemberNames.SelectContext_Option.toString());
		if (identifier != null)
			result = antselect.proxies.Option.load(context, identifier);
		return result;
	}

	/**
	 * Set value of SelectContext_Option
	 * @param selectcontext_option
	 */
	public final void setSelectContext_Option(antselect.proxies.Option selectcontext_option)
	{
		setSelectContext_Option(getContext(), selectcontext_option);
	}

	/**
	 * Set value of SelectContext_Option
	 * @param context
	 * @param selectcontext_option
	 */
	public final void setSelectContext_Option(com.mendix.systemwideinterfaces.core.IContext context, antselect.proxies.Option selectcontext_option)
	{
		if (selectcontext_option == null)
			getMendixObject().setValue(context, MemberNames.SelectContext_Option.toString(), null);
		else
			getMendixObject().setValue(context, MemberNames.SelectContext_Option.toString(), selectcontext_option.getMendixObject().getId());
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return selectContextMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final antselect.proxies.SelectContext that = (antselect.proxies.SelectContext) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "AntSelect.SelectContext";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
