// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package atlas_core.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the Atlas_Core module

	public static java.lang.String getAtlas_Core_Version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("Atlas_Core.Atlas_Core_Version");
	}
}