// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package webactions.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the WebActions module

	public static java.lang.String getWebActions_Version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("WebActions.WebActions_Version");
	}
}