// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package graph.proxies;

public class Customer
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject customerMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "Graph.Customer";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Name("Name"),
		Asset("Asset"),
		Debt("Debt"),
		Cluster("Cluster"),
		Account("Account"),
		NodeType("NodeType");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Customer(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "Graph.Customer"));
	}

	protected Customer(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject customerMendixObject)
	{
		if (customerMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("Graph.Customer", customerMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a Graph.Customer");

		this.customerMendixObject = customerMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Customer.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static graph.proxies.Customer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return graph.proxies.Customer.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static graph.proxies.Customer initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new graph.proxies.Customer(context, mendixObject);
	}

	public static graph.proxies.Customer load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return graph.proxies.Customer.initialize(context, mendixObject);
	}

	public static java.util.List<graph.proxies.Customer> load(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String xpathConstraint) throws com.mendix.core.CoreException
	{
		java.util.List<graph.proxies.Customer> result = new java.util.ArrayList<graph.proxies.Customer>();
		for (com.mendix.systemwideinterfaces.core.IMendixObject obj : com.mendix.core.Core.retrieveXPathQuery(context, "//Graph.Customer" + xpathConstraint))
			result.add(graph.proxies.Customer.initialize(context, obj));
		return result;
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Name
	 */
	public final java.lang.String getName()
	{
		return getName(getContext());
	}

	/**
	 * @param context
	 * @return value of Name
	 */
	public final java.lang.String getName(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Name.toString());
	}

	/**
	 * Set value of Name
	 * @param name
	 */
	public final void setName(java.lang.String name)
	{
		setName(getContext(), name);
	}

	/**
	 * Set value of Name
	 * @param context
	 * @param name
	 */
	public final void setName(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String name)
	{
		getMendixObject().setValue(context, MemberNames.Name.toString(), name);
	}

	/**
	 * @return value of Asset
	 */
	public final java.lang.String getAsset()
	{
		return getAsset(getContext());
	}

	/**
	 * @param context
	 * @return value of Asset
	 */
	public final java.lang.String getAsset(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Asset.toString());
	}

	/**
	 * Set value of Asset
	 * @param asset
	 */
	public final void setAsset(java.lang.String asset)
	{
		setAsset(getContext(), asset);
	}

	/**
	 * Set value of Asset
	 * @param context
	 * @param asset
	 */
	public final void setAsset(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String asset)
	{
		getMendixObject().setValue(context, MemberNames.Asset.toString(), asset);
	}

	/**
	 * @return value of Debt
	 */
	public final java.lang.String getDebt()
	{
		return getDebt(getContext());
	}

	/**
	 * @param context
	 * @return value of Debt
	 */
	public final java.lang.String getDebt(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Debt.toString());
	}

	/**
	 * Set value of Debt
	 * @param debt
	 */
	public final void setDebt(java.lang.String debt)
	{
		setDebt(getContext(), debt);
	}

	/**
	 * Set value of Debt
	 * @param context
	 * @param debt
	 */
	public final void setDebt(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String debt)
	{
		getMendixObject().setValue(context, MemberNames.Debt.toString(), debt);
	}

	/**
	 * @return value of Cluster
	 */
	public final java.lang.String getCluster()
	{
		return getCluster(getContext());
	}

	/**
	 * @param context
	 * @return value of Cluster
	 */
	public final java.lang.String getCluster(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Cluster.toString());
	}

	/**
	 * Set value of Cluster
	 * @param cluster
	 */
	public final void setCluster(java.lang.String cluster)
	{
		setCluster(getContext(), cluster);
	}

	/**
	 * Set value of Cluster
	 * @param context
	 * @param cluster
	 */
	public final void setCluster(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String cluster)
	{
		getMendixObject().setValue(context, MemberNames.Cluster.toString(), cluster);
	}

	/**
	 * @return value of Account
	 */
	public final java.lang.String getAccount()
	{
		return getAccount(getContext());
	}

	/**
	 * @param context
	 * @return value of Account
	 */
	public final java.lang.String getAccount(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Account.toString());
	}

	/**
	 * Set value of Account
	 * @param account
	 */
	public final void setAccount(java.lang.String account)
	{
		setAccount(getContext(), account);
	}

	/**
	 * Set value of Account
	 * @param context
	 * @param account
	 */
	public final void setAccount(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String account)
	{
		getMendixObject().setValue(context, MemberNames.Account.toString(), account);
	}

	/**
	 * @return value of NodeType
	 */
	public final java.lang.String getNodeType()
	{
		return getNodeType(getContext());
	}

	/**
	 * @param context
	 * @return value of NodeType
	 */
	public final java.lang.String getNodeType(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.NodeType.toString());
	}

	/**
	 * Set value of NodeType
	 * @param nodetype
	 */
	public final void setNodeType(java.lang.String nodetype)
	{
		setNodeType(getContext(), nodetype);
	}

	/**
	 * Set value of NodeType
	 * @param context
	 * @param nodetype
	 */
	public final void setNodeType(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String nodetype)
	{
		getMendixObject().setValue(context, MemberNames.NodeType.toString(), nodetype);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return customerMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final graph.proxies.Customer that = (graph.proxies.Customer) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "Graph.Customer";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
