// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies;

public class Geolocation
{
	private final com.mendix.systemwideinterfaces.core.IMendixObject geolocationMendixObject;

	private final com.mendix.systemwideinterfaces.core.IContext context;

	/**
	 * Internal name of this entity
	 */
	public static final java.lang.String entityName = "NanoflowCommons.Geolocation";

	/**
	 * Enum describing members of this entity
	 */
	public enum MemberNames
	{
		Timestamp("Timestamp"),
		Latitude("Latitude"),
		Longitude("Longitude"),
		Altitude("Altitude"),
		Accuracy("Accuracy"),
		AltitudeAccuracy("AltitudeAccuracy"),
		Heading("Heading"),
		Speed("Speed");

		private java.lang.String metaName;

		MemberNames(java.lang.String s)
		{
			metaName = s;
		}

		@java.lang.Override
		public java.lang.String toString()
		{
			return metaName;
		}
	}

	public Geolocation(com.mendix.systemwideinterfaces.core.IContext context)
	{
		this(context, com.mendix.core.Core.instantiate(context, "NanoflowCommons.Geolocation"));
	}

	protected Geolocation(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject geolocationMendixObject)
	{
		if (geolocationMendixObject == null)
			throw new java.lang.IllegalArgumentException("The given object cannot be null.");
		if (!com.mendix.core.Core.isSubClassOf("NanoflowCommons.Geolocation", geolocationMendixObject.getType()))
			throw new java.lang.IllegalArgumentException("The given object is not a NanoflowCommons.Geolocation");

		this.geolocationMendixObject = geolocationMendixObject;
		this.context = context;
	}

	/**
	 * @deprecated Use 'Geolocation.load(IContext, IMendixIdentifier)' instead.
	 */
	@java.lang.Deprecated
	public static nanoflowcommons.proxies.Geolocation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		return nanoflowcommons.proxies.Geolocation.load(context, mendixIdentifier);
	}

	/**
	 * Initialize a proxy using context (recommended). This context will be used for security checking when the get- and set-methods without context parameters are called.
	 * The get- and set-methods with context parameter should be used when for instance sudo access is necessary (IContext.createSudoClone() can be used to obtain sudo access).
	 */
	public static nanoflowcommons.proxies.Geolocation initialize(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixObject mendixObject)
	{
		return new nanoflowcommons.proxies.Geolocation(context, mendixObject);
	}

	public static nanoflowcommons.proxies.Geolocation load(com.mendix.systemwideinterfaces.core.IContext context, com.mendix.systemwideinterfaces.core.IMendixIdentifier mendixIdentifier) throws com.mendix.core.CoreException
	{
		com.mendix.systemwideinterfaces.core.IMendixObject mendixObject = com.mendix.core.Core.retrieveId(context, mendixIdentifier);
		return nanoflowcommons.proxies.Geolocation.initialize(context, mendixObject);
	}

	/**
	 * Commit the changes made on this proxy object.
	 */
	public final void commit() throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Commit the changes made on this proxy object using the specified context.
	 */
	public final void commit(com.mendix.systemwideinterfaces.core.IContext context) throws com.mendix.core.CoreException
	{
		com.mendix.core.Core.commit(context, getMendixObject());
	}

	/**
	 * Delete the object.
	 */
	public final void delete()
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}

	/**
	 * Delete the object using the specified context.
	 */
	public final void delete(com.mendix.systemwideinterfaces.core.IContext context)
	{
		com.mendix.core.Core.delete(context, getMendixObject());
	}
	/**
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp()
	{
		return getTimestamp(getContext());
	}

	/**
	 * @param context
	 * @return value of Timestamp
	 */
	public final java.util.Date getTimestamp(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.util.Date) getMendixObject().getValue(context, MemberNames.Timestamp.toString());
	}

	/**
	 * Set value of Timestamp
	 * @param timestamp
	 */
	public final void setTimestamp(java.util.Date timestamp)
	{
		setTimestamp(getContext(), timestamp);
	}

	/**
	 * Set value of Timestamp
	 * @param context
	 * @param timestamp
	 */
	public final void setTimestamp(com.mendix.systemwideinterfaces.core.IContext context, java.util.Date timestamp)
	{
		getMendixObject().setValue(context, MemberNames.Timestamp.toString(), timestamp);
	}

	/**
	 * @return value of Latitude
	 */
	public final java.lang.String getLatitude()
	{
		return getLatitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Latitude
	 */
	public final java.lang.String getLatitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Latitude.toString());
	}

	/**
	 * Set value of Latitude
	 * @param latitude
	 */
	public final void setLatitude(java.lang.String latitude)
	{
		setLatitude(getContext(), latitude);
	}

	/**
	 * Set value of Latitude
	 * @param context
	 * @param latitude
	 */
	public final void setLatitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String latitude)
	{
		getMendixObject().setValue(context, MemberNames.Latitude.toString(), latitude);
	}

	/**
	 * @return value of Longitude
	 */
	public final java.lang.String getLongitude()
	{
		return getLongitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Longitude
	 */
	public final java.lang.String getLongitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Longitude.toString());
	}

	/**
	 * Set value of Longitude
	 * @param longitude
	 */
	public final void setLongitude(java.lang.String longitude)
	{
		setLongitude(getContext(), longitude);
	}

	/**
	 * Set value of Longitude
	 * @param context
	 * @param longitude
	 */
	public final void setLongitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String longitude)
	{
		getMendixObject().setValue(context, MemberNames.Longitude.toString(), longitude);
	}

	/**
	 * @return value of Altitude
	 */
	public final java.lang.String getAltitude()
	{
		return getAltitude(getContext());
	}

	/**
	 * @param context
	 * @return value of Altitude
	 */
	public final java.lang.String getAltitude(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Altitude.toString());
	}

	/**
	 * Set value of Altitude
	 * @param altitude
	 */
	public final void setAltitude(java.lang.String altitude)
	{
		setAltitude(getContext(), altitude);
	}

	/**
	 * Set value of Altitude
	 * @param context
	 * @param altitude
	 */
	public final void setAltitude(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String altitude)
	{
		getMendixObject().setValue(context, MemberNames.Altitude.toString(), altitude);
	}

	/**
	 * @return value of Accuracy
	 */
	public final java.lang.String getAccuracy()
	{
		return getAccuracy(getContext());
	}

	/**
	 * @param context
	 * @return value of Accuracy
	 */
	public final java.lang.String getAccuracy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Accuracy.toString());
	}

	/**
	 * Set value of Accuracy
	 * @param accuracy
	 */
	public final void setAccuracy(java.lang.String accuracy)
	{
		setAccuracy(getContext(), accuracy);
	}

	/**
	 * Set value of Accuracy
	 * @param context
	 * @param accuracy
	 */
	public final void setAccuracy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String accuracy)
	{
		getMendixObject().setValue(context, MemberNames.Accuracy.toString(), accuracy);
	}

	/**
	 * @return value of AltitudeAccuracy
	 */
	public final java.lang.String getAltitudeAccuracy()
	{
		return getAltitudeAccuracy(getContext());
	}

	/**
	 * @param context
	 * @return value of AltitudeAccuracy
	 */
	public final java.lang.String getAltitudeAccuracy(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.AltitudeAccuracy.toString());
	}

	/**
	 * Set value of AltitudeAccuracy
	 * @param altitudeaccuracy
	 */
	public final void setAltitudeAccuracy(java.lang.String altitudeaccuracy)
	{
		setAltitudeAccuracy(getContext(), altitudeaccuracy);
	}

	/**
	 * Set value of AltitudeAccuracy
	 * @param context
	 * @param altitudeaccuracy
	 */
	public final void setAltitudeAccuracy(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String altitudeaccuracy)
	{
		getMendixObject().setValue(context, MemberNames.AltitudeAccuracy.toString(), altitudeaccuracy);
	}

	/**
	 * @return value of Heading
	 */
	public final java.lang.String getHeading()
	{
		return getHeading(getContext());
	}

	/**
	 * @param context
	 * @return value of Heading
	 */
	public final java.lang.String getHeading(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Heading.toString());
	}

	/**
	 * Set value of Heading
	 * @param heading
	 */
	public final void setHeading(java.lang.String heading)
	{
		setHeading(getContext(), heading);
	}

	/**
	 * Set value of Heading
	 * @param context
	 * @param heading
	 */
	public final void setHeading(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String heading)
	{
		getMendixObject().setValue(context, MemberNames.Heading.toString(), heading);
	}

	/**
	 * @return value of Speed
	 */
	public final java.lang.String getSpeed()
	{
		return getSpeed(getContext());
	}

	/**
	 * @param context
	 * @return value of Speed
	 */
	public final java.lang.String getSpeed(com.mendix.systemwideinterfaces.core.IContext context)
	{
		return (java.lang.String) getMendixObject().getValue(context, MemberNames.Speed.toString());
	}

	/**
	 * Set value of Speed
	 * @param speed
	 */
	public final void setSpeed(java.lang.String speed)
	{
		setSpeed(getContext(), speed);
	}

	/**
	 * Set value of Speed
	 * @param context
	 * @param speed
	 */
	public final void setSpeed(com.mendix.systemwideinterfaces.core.IContext context, java.lang.String speed)
	{
		getMendixObject().setValue(context, MemberNames.Speed.toString(), speed);
	}

	/**
	 * @return the IMendixObject instance of this proxy for use in the Core interface.
	 */
	public final com.mendix.systemwideinterfaces.core.IMendixObject getMendixObject()
	{
		return geolocationMendixObject;
	}

	/**
	 * @return the IContext instance of this proxy, or null if no IContext instance was specified at initialization.
	 */
	public final com.mendix.systemwideinterfaces.core.IContext getContext()
	{
		return context;
	}

	@java.lang.Override
	public boolean equals(Object obj)
	{
		if (obj == this)
			return true;

		if (obj != null && getClass().equals(obj.getClass()))
		{
			final nanoflowcommons.proxies.Geolocation that = (nanoflowcommons.proxies.Geolocation) obj;
			return getMendixObject().equals(that.getMendixObject());
		}
		return false;
	}

	@java.lang.Override
	public int hashCode()
	{
		return getMendixObject().hashCode();
	}

	/**
	 * @return String name of this class
	 */
	public static java.lang.String getType()
	{
		return "NanoflowCommons.Geolocation";
	}

	/**
	 * @return String GUID from this object, format: ID_0000000000
	 * @deprecated Use getMendixObject().getId().toLong() to get a unique identifier for this object.
	 */
	@java.lang.Deprecated
	public java.lang.String getGUID()
	{
		return "ID_" + getMendixObject().getId().toLong();
	}
}
