// This file was generated by Mendix Studio Pro.
//
// WARNING: Code you write here will be lost the next time you deploy the project.

package nanoflowcommons.proxies.constants;

import com.mendix.core.Core;

public class Constants
{
	// These are the constants for the NanoflowCommons module

	public static java.lang.String getNanoflow_Commons_Version()
	{
		return (java.lang.String)Core.getConfiguration().getConstantValue("NanoflowCommons.Nanoflow_Commons_Version");
	}
}