/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[0],{336:function(ha,ca,h){h.r(ca);h.d(ca,"ByteRangeRequest",function(){return ka});var ba=h(2),da=h(0);h.n(da);var fa=h(1),aa=h(116);ha=h(74);var z=h(145),y=h(64),w=h(53),f=h(193),n=h(131);h=h(290);var x=[],e=[],r=window,ea=function(){return function(){this.fk=1}}(),ia;(function(e){e[e.UNSENT=0]="UNSENT";e[e.DONE=4]="DONE"})(ia||(ia={}));var ka=function(){function h(e,h,n,w){var x=this;this.url=e;this.range=h;this.tf=n;this.withCredentials=
w;this.AQ=ia;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);r.Uint8Array&&(this.request.responseType="arraybuffer");w&&(this.request.withCredentials=w);oa.DISABLE_RANGE_HEADER||(Object(da.isUndefined)(h.stop)?this.request.setRequestHeader("Range","bytes="+h.start):this.request.setRequestHeader("Range",["bytes=",h.start,"-",h.stop-1].join("")));this.request.setRequestHeader("X-Requested-With","XMLHttpRequest");n&&Object.keys(n).forEach(function(e){x.request.setRequestHeader(e,
n[e])});this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=f.a.NOT_STARTED}h.prototype.start=function(e){var h=this,n=this.request;n.onreadystatechange=function(){if(h.aborted)return h.status=f.a.ABORTED,e({code:f.a.ABORTED});if(this.readyState===h.AQ.DONE){h.Ew();var w=0===window.document.URL.indexOf("file:///");200===n.status||206===n.status||w&&0===n.status?(w=r.nK(this),
h.cq(w,e)):(h.status=f.a.ERROR,e({code:h.status,status:this.status}))}};this.request.send(null);this.status=f.a.STARTED};h.prototype.cq=function(e,h){this.status=f.a.SUCCESS;if(h)return h(!1,e)};h.prototype.abort=function(){this.Ew();this.aborted=!0;this.request.abort()};h.prototype.Ew=function(){var f=Object(n.b)(this.url,this.range,e);-1!==f&&e.splice(f,1);if(0<x.length){f=x.shift();var r=new h(f.url,f.range,this.tf,this.withCredentials);f.request=r;e.push(f);r.start(Object(n.c)(f))}};h.prototype.extend=
function(e){var f=Object.assign({},this,e.prototype);f.constructor=e;return f};return h}(),oa=function(f){function h(e,h,n,r,w){n=f.call(this,e,n,r)||this;n.hk={};n.uv=h;n.url=e;n.DISABLE_RANGE_HEADER=!1;n.dt=ka;n.gF=3;n.tf=w||{};return n}Object(ba.c)(h,f);h.prototype.pr=function(e,f,h){var n=-1===e.indexOf("?")?"?":"&";switch(h){case !1:case w.a.NEVER_CACHE:e=e+n+"_="+Object(da.uniqueId)();break;case !0:case ["CacheHinting.CACHE"]:e=e+n+"_="+f.start+","+(Object(da.isUndefined)(f.stop)?"":f.stop)}return e};
h.prototype.CI=function(e,f,h,n){void 0===h&&(h={});return new this.dt(e,f,h,n)};h.prototype.HV=function(f,h,n,r,w){for(var y=0;y<x.length;y++)if(Object(da.isEqual)(x[y].range,h)&&Object(da.isEqual)(x[y].url,f))return x[y].Mf.push(r),x[y].wx++,null;for(y=0;y<e.length;y++)if(Object(da.isEqual)(e[y].range,h)&&Object(da.isEqual)(e[y].url,f))return e[y].Mf.push(r),e[y].wx++,null;n={url:f,range:h,uv:n,Mf:[r],wx:1};if(0===x.length&&e.length<this.gF)return e.push(n),n.request=this.CI(f,h,w,this.withCredentials),
n;x.push(n);return null};h.prototype.ll=function(f,h,r){var w=this.pr(f,h,this.uv);(f=this.HV(w,h,this.uv,r,this.tf))&&f.request.start(Object(n.c)(f));return function(){var f=Object(n.b)(w,h,e);if(-1!==f){var r=--e[f].wx;0===r&&e[f].request&&e[f].request.abort()}else f=Object(n.b)(w,h,x),-1!==f&&(r=--x[f].wx,0===r&&x.splice(f,1))}};h.prototype.VJ=function(){return{start:-aa.a}};h.prototype.fY=function(){var e=-(aa.a+aa.e);return{start:e-aa.d,end:e}};h.prototype.vp=function(e){var f=this;this.zv=!0;
var h=aa.a;this.ll(this.url,this.VJ(),function(n,r,w){function x(){var h=f.vd.SJ();f.ll(f.url,h,function(n,r){if(n)return Object(fa.h)("Error loading central directory: "+n),e(n);r=Object(y.a)(r);if(r.length!==h.stop-h.start)return e("Invalid XOD file: Zip central directory data is wrong size! Should be "+(h.stop-h.start)+" but is "+r.length);f.vd.CM(r);f.CA=!0;f.zv=!1;return e(!1)})}if(n)return Object(fa.h)("Error loading end header: "+n),e(n,r,w);r=Object(y.a)(r);if(r.length!==h)return e("Invalid XOD file: Zip end header data is wrong size!");
try{f.vd=new z.a(r)}catch(va){return e(va)}f.vd.uZ?f.ll(f.url,f.fY(),function(h,n){if(h)return Object(fa.h)("Error loading zip64 header: "+h),e(h);n=Object(y.a)(n);f.vd.IZ(n);x()}):x()})};h.prototype.kK=function(e){e(Object.keys(this.vd.Yk))};h.prototype.jD=function(e,f){var h=this;if(this.vd.uI(e)){var n=this.vd.ww(e);if(n in this.hk){var r=this.Gg[e];r.Io=this.hk[n];r.Io.fk++;r.cancel=r.Io.cancel}else{var w=this.vd.KW(e),x=this.ll(this.url,w,function(r,x){r?(Object(fa.h)('Error loading part "'+
e+'": '+r),h.ll(h.url,w,function(r,x){if(r)return f(r,e);h.DM(x,w,n,e,f)})):h.DM(x,w,n,e,f)}),y=this.Gg[e];y&&(y.kO=!0,y.cancel=function(){y.Io.fk--;0===y.Io.fk&&(x(),delete h.hk[n])},this.hk[n]=new ea(n),y.Io=this.hk[n],y.Io.cancel=y.cancel)}}else delete this.Gg[e],f(Error('File not found: "'+e+'"'),e)};h.prototype.DM=function(e,f,h,n,r){if(e.length!==f.stop-f.start)r(Error("Part data is wrong size!"),n);else{do{if(!this.hk[h])return;n=this.hk[h].fk;for(var w=f.BM.length,x=0;x<w;++x){var y=f.BM[x];
r(!1,y.sn,e["string"===typeof e?"substring":"subarray"](y.start,y.stop),this.vd.iL(y.sn));y.sn in this.Gg&&delete this.Gg[y.sn]}}while(n!==this.hk[h].fk);delete this.hk[h]}};h.DISABLE_RANGE_HEADER=!1;h.gF=3;return h}(ha.a);(function(e){function f(f,h,n){var r=e.call(this)||this,w;for(w in f)r[w]=f[w];r.l6=f;r.startOffset=h;r.endOffset=n;r.CI=function(e,h,n,w){Object(da.isUndefined)(h.stop)?(h.start+=r.endOffset,h.stop=r.endOffset):(h.start+=r.startOffset,h.stop+=r.startOffset);e=r.pr(r.url,h,r.uv);
return new f.dt(e,h,n,w)};return r}Object(ba.c)(f,e);return f})(oa);Object(h.a)(oa);Object(h.b)(oa);ca["default"]=oa}}]);}).call(this || window)
