/** Notice * This file contains works from many authors under various (but compatible) licenses. Please see legal.txt for more information. **/
(function(){(window.wpCoreControlsBundle=window.wpCoreControlsBundle||[]).push([[12],{344:function(ha,ca,h){h.r(ca);var ba=h(2),da=h(0);h.n(da);var fa=h(1),aa=h(116);ha=h(35);var z=h(74),y=h(145),w=h(53),f=h(193);h=h(290);var n=window,x=function(){function e(e,h,n){var r=-1===e.indexOf("?")?"?":"&";switch(h){case w.a.e4:this.url=e+r+"_="+Object(da.uniqueId)();break;default:this.url=e}this.tf=n;this.request=new XMLHttpRequest;this.request.open("GET",this.url,!0);this.request.setRequestHeader("X-Requested-With",
"XMLHttpRequest");this.request.overrideMimeType?this.request.overrideMimeType("text/plain; charset=x-user-defined"):this.request.setRequestHeader("Accept-Charset","x-user-defined");this.status=f.a.NOT_STARTED}e.prototype.start=function(h,n){var r=this,w=this,x=this.request,y;w.Bs=0;h&&Object.keys(h).forEach(function(e){r.request.setRequestHeader(e,h[e])});n&&(this.request.withCredentials=n);this.Ox=setInterval(function(){var h=0===window.document.URL.indexOf("file:///");h=200===x.status||h&&0===x.status;
if(x.readyState!==f.b.DONE||h){try{x.responseText}catch(ua){return}w.Bs<x.responseText.length&&(y=w.P_())&&w.trigger(e.Events.DATA,[y]);0===x.readyState&&(clearInterval(w.Ox),w.trigger(e.Events.DONE))}else clearInterval(w.Ox),w.trigger(e.Events.DONE,["Error received return status "+x.status])},1E3);this.request.send(null);this.status=f.a.STARTED};e.prototype.P_=function(){var f=this.request,h=f.responseText;if(0!==h.length)if(this.Bs===h.length)clearInterval(this.Ox),this.trigger(e.Events.DONE);else return h=
Math.min(this.Bs+3E6,h.length),f=n.nK(f,this.Bs,!0,h),this.Bs=h,f};e.prototype.abort=function(){clearInterval(this.Ox);var h=this;this.request.onreadystatechange=function(){Object(fa.h)("StreamingRequest aborted");h.status=f.a.ABORTED;return h.trigger(e.Events.ABORTED)};this.request.abort()};e.prototype.finish=function(){var h=this;this.request.onreadystatechange=function(){h.status=f.a.SUCCESS;return h.trigger(e.Events.DONE)};this.request.abort()};e.Events={DONE:"done",DATA:"data",ABORTED:"aborted"};
return e}();Object(ha.b)(x);var e;(function(e){e[e.LOCAL_HEADER=0]="LOCAL_HEADER";e[e.FILE=1]="FILE";e[e.CENTRAL_DIR=2]="CENTRAL_DIR"})(e||(e={}));var r=function(f){function h(){var h=f.call(this)||this;h.buffer="";h.state=e.LOCAL_HEADER;h.kE=4;h.Sj=null;h.zp=aa.c;h.Yk={};return h}Object(ba.c)(h,f);h.prototype.L_=function(f){var n;for(f=this.buffer+f;f.length>=this.zp;)switch(this.state){case e.LOCAL_HEADER:this.Sj=n=this.S_(f.slice(0,this.zp));if(n.Wp!==aa.g)throw Error("Wrong signature in local header: "+
n.Wp);f=f.slice(this.zp);this.state=e.FILE;this.zp=n.tA+n.mn+n.Hr+this.kE;this.trigger(h.Events.HEADER,[n]);break;case e.FILE:this.Sj.name=f.slice(0,this.Sj.mn);this.Yk[this.Sj.name]=this.Sj;n=this.zp-this.kE;var r=f.slice(this.Sj.mn+this.Sj.Hr,n);this.trigger(h.Events.FILE,[this.Sj.name,r,this.Sj.IA]);f=f.slice(n);if(f.slice(0,this.kE)===aa.h)this.state=e.LOCAL_HEADER,this.zp=aa.c;else return this.state=e.CENTRAL_DIR,!0}this.buffer=f;return!1};h.Events={HEADER:"header",FILE:"file"};return h}(y.a);
Object(ha.b)(r);ha=function(e){function f(f,h,n,w,y){n=e.call(this,f,n,w)||this;n.url=f;n.stream=new x(f,h);n.vd=new r;n.rM=window.createPromiseCapability();n.HM={};n.tf=y;return n}Object(ba.c)(f,e);f.prototype.nt=function(e){var f=this;this.request([this.Oh,this.Ri,this.Nh]);this.stream.on(x.Events.DATA,function(h){try{if(f.vd.L_(h))return f.stream.finish()}catch(la){throw f.stream.abort(),f.Er(la),e(la),la;}});this.stream.on(x.Events.DONE,function(h){f.x_=!0;f.rM.resolve();h&&(f.Er(h),e(h))});this.vd.on(r.Events.HEADER,
Object(da.bind)(this.GM,this));this.vd.on(r.Events.FILE,Object(da.bind)(this.V_,this));return this.stream.start(this.tf,this.withCredentials)};f.prototype.kK=function(e){var f=this;this.rM.promise.then(function(){e(Object.keys(f.vd.Yk))})};f.prototype.wl=function(){return!0};f.prototype.request=function(e){var f=this;this.x_&&e.forEach(function(e){f.HM[e]||f.c3(e)})};f.prototype.GM=function(){};f.prototype.abort=function(){this.stream&&this.stream.abort()};f.prototype.c3=function(e){this.trigger(z.a.Events.PART_READY,
[{Wa:e,error:"Requested part not found",Xg:!1,rf:!1}])};f.prototype.V_=function(e,f,h){this.HM[e]=!0;this.trigger(z.a.Events.PART_READY,[{Wa:e,data:f,Xg:!1,rf:!1,error:null,Lc:h}])};return f}(z.a);Object(h.a)(ha);Object(h.b)(ha);ca["default"]=ha}}]);}).call(this || window)
